### ISSUE TITLE
Authentication Information/Clarification

### ISSUE THREAD

**Issue by edman007** [kaedenbrinkman/rivian-api#8]
So I'm trying to write a script to eventually call GetVehicleState and read that.

I'm currently getting "unauthenticated" error after successfully calling the authentication commands, I think I'm having trouble understanding the authentication process. It would be super helpful if the docs included a sample program that executed some of the calls.

Some of the confusing things I see:

1. Under authentication it says "Authentication involves requesting a CSRF token and then using that token to request an access token via your login credentials. The access token is used to authenticate all other API requests.". Are two tokens used used for other requests? The CSRF and the Access Token? Does that me the function of the "refreshToken" and "userSessionToken" are unknown?
2. All the commands seem to say that these are the required headers:
```
a-sess: <your app session token>
u-sess: <your user session token>
csrf-token: <your CSRF token>
```
Is that correct? The App Token isn't used? It's just the App Session Token (from the first authentication request)? Because I tried that specifically and it doesn't work. So I think something is in conflict with the statements made under authentication.
3. Anything you know about token lifecycles would be awesome to document (if you know the how fast the app refreshes them), and I assume the refreshToken is actually for token refreshes

A simple script that you can execute and prove it works would help immensely (and if the API changed, it could be used to identify that)

**Comment by kaedenbrinkman** [comment]
Hi Ed,
I would suggest you check out https://github.com/the-mace/rivian-python-api for some examples. I am no longer able to directly contribute to this repository, but if you would like to contribute and add more information or improve the documentation I would be happy to merge a PR.
